# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ae2746a39e5c6a2b8ea24084f17e3d806587ab0e4d84828f119e1c65629f03e79c752c5b3a1cb4bf6c35c467da74c1774a058ee5ec21265f9388670371e9e7

test:
  secret_key_base: 75925f984ffc1f0c426f10c4ba95e4b5289b9d83b430bdef05fabbfd88202ec37a89e71d7a8d3d19d1b1f8348b3b7ee08f51912ffc0839ecc9d8370efe6c9764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
